# ã‚«ã‚¹ã‚¿ãƒ ãƒ•ã‚©ãƒ¼ãƒãƒƒãƒˆã‚’åˆ©ç”¨ã—ã¾ã™
# format = ""

scan_timeout = 10

[aws]
disabled = true

[battery]

[[battery.display]]
threshold = 10
style = "bold red"

[character]
success_symbol = "[ğŸ‘]()"
error_symbol = "[ğŸ‘]()"

[directory]
truncation_length = 10
truncation_symbol = "~/"

[docker_context]
format = "via [ğŸ‹ $context](blue bold) "

[git_branch]
always_show_remote = true
symbol = "ğŸŒ± "
style = "bold green"
truncation_symbol = ""

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
up_to_date = "âœ…"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"
